In [3]:
import numpy as np 
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [4]:
df=pd.read_csv("C:/Program Files (x86)/New excel/tested.csv")[['Age', 'Pclass', 'SibSp', 'Parch', 'Survived']]

In [5]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  34.5       3      0      0         0
1  47.0       3      1      0         1
2  62.0       2      0      0         0
3  27.0       3      0      0         0
4  22.0       3      1      1         1

In [6]:
df.dropna(inplace=True)

In [7]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  34.5       3      0      0         0
1  47.0       3      1      0         1
2  62.0       2      0      0         0
3  27.0       3      0      0         0
4  22.0       3      1      1         1

In [9]:
#seprate
X = df.iloc[:,0:4]
y = df.iloc[:, -1]

In [10]:
X.head()

    Age  Pclass  SibSp  Parch
0  34.5       3      0      0
1  47.0       3      1      0
2  62.0       2      0      0
3  27.0       3      0      0
4  22.0       3      1      1

In [12]:
#cross validate 20 times 
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6238970588235293)

In [14]:
#feature construction apply
X['Family_Size'] = X['SibSp'] + X['Parch'] + 1

In [15]:
X.head()

    Age  Pclass  SibSp  Parch  Family_Size
0  34.5       3      0      0            1
1  47.0       3      1      0            2
2  62.0       2      0      0            1
3  27.0       3      0      0            1
4  22.0       3      1      1            3

In [17]:
def myfunc(num):
    if num == 1:
        #alone
        return 0 
    elif num >1 and num <=4:
        #small family 
        return 1 
    else:
        #large family
        return 2

In [18]:
myfunc(4)

1

In [21]:
X['Family_type'] = X['Family_Size'].apply(myfunc)

In [22]:
X.head()

    Age  Pclass  SibSp  Parch  Family_Size  Family_type
0  34.5       3      0      0            0            2
1  47.0       3      1      0            1            0
2  62.0       2      0      0            0            2
3  27.0       3      0      0            0            2
4  22.0       3      1      1            1            0

In [24]:
X.drop(columns=['SibSp','Parch','Family_Size'], inplace=True)

In [25]:
X.head()

    Age  Pclass  Family_type
0  34.5       3            2
1  47.0       3            0
2  62.0       2            2
3  27.0       3            2
4  22.0       3            0

In [26]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6216911764705882)

In [27]:
#Feature spliting
df=pd.read_csv("C:/Program Files (x86)/New excel/tested.csv")

In [28]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [29]:
df['Name']

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

In [30]:
df['Title'] = df['Name'].str.split(', ',expand=True)[1].str.split('.', expand=True)[0]

In [32]:
df[['Title', 'Name']]

      Title                                          Name
0        Mr                              Kelly, Mr. James
1       Mrs              Wilkes, Mrs. James (Ellen Needs)
2        Mr                     Myles, Mr. Thomas Francis
3        Mr                              Wirz, Mr. Albert
4       Mrs  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..      ...                                           ...
413      Mr                            Spector, Mr. Woolf
414    Dona                  Oliva y Ocana, Dona. Fermina
415      Mr                  Saether, Mr. Simon Sivertsen
416      Mr                           Ware, Mr. Frederick
417  Master                      Peter, Master. Michael J

[418 rows x 2 columns]

In [34]:
df['Is_Married'] = 0
df['Is_Married'].loc[df['Title'] == 'Mrs']= 1

C:\Users\III S I\AppData\Local\Temp\ipykernel_8164\1816490417.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Is_Married'].loc[df['Title'] == 'Mrs']= 1
C:\Users\III S I\AppData\Local\Temp\ipykernel_8164\1816490417.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Is_Married'].loc[df['Title'] == 'Mrs']= 1

In [35]:
df['Is_Married']

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    0
415    0
416    0
417    0
Name: Is_Married, Length: 418, dtype: int64